epochs: 30

batch_size: 64

learning_rate: 0.001

steering_correction: 0.2

augmentation_prob: 0.5  

train_split: 0.8        

#learning rate scheduler
lr_patience: 5
lr_factor: 0.5

#early stopping
early_stopping_patience: 15